version: '3'

services:
  php-fpm:
    build:
      context: /home/dockers/Reptichart_Docker/php-fpm
    restart: unless-stopped
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./server/config.ini:/var/www/html/includes/config.ini
      - ./src/public_html:/var/www/html
      - ./php-fpm/logs:/var/log/php
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      
  nginx:
    build:
      context: /home/dockers/Reptichart_Docker/nginx
    restart: unless-stopped
    volumes:
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./src/ssl:/ssl/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - php-fpm

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  server:
    build:
      context: /home/dockers/Reptichart_Docker/server
    restart: unless-stopped
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
    ports:
        - "65432:65432"
        - "65433:65433"
        - "65434:65434"
        - "65435:65435"
        - "65436:65436"
        - "65437:65437"
