version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./server/config.ini:/var/www/html/includes/config.ini
      - ./src/public_html:/var/www/html
      - ./php-fpm/logs:/var/log/php
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm




  server:
    build:
      context: ./server
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
    ports:
        - "65432:65432"
        - "65433:65433"
        - "65434:65434"
        - "65435:65435"
        - "65436:65436"
        - "65437:65437"
