version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
      
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/db/reptichart_readings.db:/reptichart_readings.db
      - ./src/public_html:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm




#  server:
