version: '3'

context: /home/reptichart/Reptichart_Docker/
services:
  php-fpm:
    build:
      context: /home/reptichart/Reptichart_Docker/php-fpm
    volumes:
      - /home/reptichart/Reptichart_Docker/server/db/reptichart_readings.db:/reptichart_readings.db
      - /home/reptichart/Reptichart_Docker/server/config.ini:/var/www/html/includes/config.ini
      - /home/reptichart/Reptichart_Docker/src/public_html:/var/www/html
      - /home/reptichart/Reptichart_Docker/php-fpm/logs:/var/log/php
      - /home/reptichart/Reptichart_Docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      
  nginx:
    build:
      context: /home/reptichart/Reptichart_Docker/nginx
    volumes:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/reptichart/Reptichart_Docker/server/db/reptichart_readings.db:/reptichart_readings.db
      - /home/reptichart/Reptichart_Docker/src/public_html:/var/www/html
      - /home/reptichart/Reptichart_Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/reptichart/Reptichart_Docker/nginx/sites/:/etc/nginx/sites-available
      - /home/reptichart/Reptichart_Docker/nginx/conf.d/:/etc/nginx/conf.d
      - /home/reptichart/Reptichart_Docker/nginx/logs:/var/log/nginx
      - /home/reptichart/Reptichart_Docker/src/ssl:/ssl/
    depends_on:
      - php-fpm

  server:
    build:
      context: /home/reptichart/Reptichart_Docker/server
    volumes:
      - /home/reptichart/Reptichart_Docker/server/db/reptichart_readings.db:/reptichart_readings.db
    ports:
        - "65432:65432"
        - "65433:65433"
        - "65434:65434"
        - "65435:65435"
        - "65436:65436"
        - "65437:65437"
